services:
  - type: web
    name: plataforma-subastas
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      # Añade aquí el resto de variables de entorno, incluidas las de la base de datos
    autoDeploy: true
